// AUTO-GENERATED by `npm run gen:gallery` (scripts/generate-gallery-data.ts). Do not edit by hand --
// edit graphics.data.ts instead and regenerate (this also runs automatically before `dev`/`build`).

export const pics: Pic[] = [
  { src: "/images/gallery/graphics/Andres BC All Stars Game.png", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/Varsity Poster Final.jpg", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/488968301_1765443150672408_7674308146999412494_n.jpg", width: 1170, height: 1560 },
  { src: "/graphics/Nathan Lowden Queens Commit Final.jpg", width: 1760, height: 2200 },
  { src: "/images/gallery/graphics/FINAL 6273341.jpg", width: 2160, height: 2160 },
  { src: "/images/gallery/graphics/Prov Sec.jpg", width: 1080, height: 1350 },
  { src: "/images/gallery/graphics/lucasgonzales.jpg", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/Saints day post.jpg", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/Senior day post.jpg", width: 1637, height: 2200 },
  { src: "/images/gallery/graphics/24 hours.png", width: 1080, height: 1350 },
  { src: "/images/gallery/graphics/V3 6238121.jpg", width: 2160, height: 2160 },
  { src: "/images/gallery/graphics/Winner.jpg", width: 2200, height: 1467 },
  { src: "/images/gallery/graphics/VC Football Senior Day Jerome.png", width: 1000, height: 1250 },
];

export const mobilePics: Pic[] = [
  { src: "/images/gallery/graphics/Andres BC All Stars Game.png", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/Varsity Poster Final.jpg", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/488968301_1765443150672408_7674308146999412494_n.jpg", width: 1170, height: 1560 },
  { src: "/graphics/Nathan Lowden Queens Commit Final.jpg", width: 1760, height: 2200 },
  { src: "/images/gallery/graphics/FINAL 6273341.jpg", width: 2160, height: 2160 },
  { src: "/images/gallery/graphics/Prov Sec.jpg", width: 1080, height: 1350 },
  { src: "/images/gallery/graphics/lucasgonzales.jpg", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/Saints day post.jpg", width: 1650, height: 2200 },
  { src: "/images/gallery/graphics/Senior day post.jpg", width: 1637, height: 2200 },
  { src: "/images/gallery/graphics/24 hours.png", width: 1080, height: 1350 },
  { src: "/images/gallery/graphics/V3 6238121.jpg", width: 2160, height: 2160 },
  { src: "/images/gallery/graphics/Winner.jpg", width: 2200, height: 1467 },
  { src: "/images/gallery/graphics/VC Football Senior Day Jerome.png", width: 1000, height: 1250 },
];
