/**
 * Reads each gallery's hand-curated `<name>.data.ts` (filenames + layout flags only)
 * and writes `<name>.generated.ts` (the actual `Pic[]` arrays the page imports),
 * resolving each entry against the real file on disk and reading its real
 * width/height via sharp -- dimensions are never hand-typed.
 *
 * Run automatically before `dev`/`build` (see package.json `predev`/`prebuild`).
 * Fails loudly (non-zero exit) if a curated entry points at a file that doesn't
 * exist, rather than silently baking in a broken path.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import sharp from "sharp";
import type { CuratedEntry } from "../lib/galleryTypes";

const REPO_ROOT = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(REPO_ROOT, "public");

const GALLERIES = [
  { name: "sports", dir: path.join(REPO_ROOT, "app/portfolio/sports") },
  { name: "portraits", dir: path.join(REPO_ROOT, "app/portfolio/portraits") },
  { name: "graphics", dir: path.join(REPO_ROOT, "app/portfolio/graphics") },
];

interface GeneratedPic {
  src: string;
  width: number;
  height: number;
  big?: true;
  quality?: number;
}

async function resolveEntry(entry: CuratedEntry, defaultDir: string): Promise<GeneratedPic> {
  const dir = entry.dir ?? defaultDir;
  const absPath = path.join(PUBLIC_DIR, dir, entry.file);
  if (!fs.existsSync(absPath)) {
    throw new Error(`Gallery entry references a file that does not exist: ${absPath}`);
  }

  const metadata = await sharp(absPath).metadata();
  if (!metadata.width || !metadata.height) {
    throw new Error(`Could not read dimensions for: ${absPath}`);
  }

  const pic: GeneratedPic = {
    src: "/" + path.posix.join(dir, entry.file),
    width: metadata.width,
    height: metadata.height,
  };
  if (entry.big) pic.big = true;
  if (entry.quality !== undefined) pic.quality = entry.quality;
  return pic;
}

function serializePic(pic: GeneratedPic): string {
  const parts: string[] = [`src: ${JSON.stringify(pic.src)}`, `width: ${pic.width}`, `height: ${pic.height}`];
  if (pic.big) parts.push("big: true");
  if (pic.quality !== undefined) parts.push(`quality: ${pic.quality}`);
  return `  { ${parts.join(", ")} },`;
}

function serializeArray(name: string, pics: GeneratedPic[]): string {
  const lines = pics.map(serializePic).join("\n");
  return `export const ${name}: Pic[] = [\n${lines}\n];\n`;
}

async function generateGallery(name: string, dir: string) {
  const dataModule = await import(pathToFileURL(path.join(dir, `${name}.data.ts`)).href);
  const defaultDir: string = dataModule.dir ?? "";

  const desktopEntries: CuratedEntry[] = dataModule.desktop;
  const mobileEntries: CuratedEntry[] = dataModule.mobile;

  const pics = await Promise.all(desktopEntries.map((e) => resolveEntry(e, defaultDir)));
  const mobilePics = await Promise.all(mobileEntries.map((e) => resolveEntry(e, defaultDir)));

  const header = `// AUTO-GENERATED by \`npm run gen:gallery\` (scripts/generate-gallery-data.ts). Do not edit by hand --\n// edit ${name}.data.ts instead and regenerate (this also runs automatically before \`dev\`/\`build\`).\n\n`;
  const body = serializeArray("pics", pics) + "\n" + serializeArray("mobilePics", mobilePics);

  const outPath = path.join(dir, `${name}.generated.ts`);
  fs.writeFileSync(outPath, header + body);
  console.log(`Wrote ${outPath} (${pics.length} desktop, ${mobilePics.length} mobile)`);
}

async function main() {
  for (const gallery of GALLERIES) {
    await generateGallery(gallery.name, gallery.dir);
  }
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
